__name__ = 'mdrnn'
__version__ = '0.2.2'
__author__ = 'Evgenii Dolotov'
__author_email__ = 'supernovaprotocol@gmail.com'
__description__ = 'A library implementing multi-dimensional recurrent neural networks'
__url__ = 'https://github.com/X-rayLaser/multi-directional-mdrnn'
